#!/usr/bin/env python3

import json
from configparser import ConfigParser
from pathlib import Path

import click

aws = Path.home() / '.aws'


@click.command(help='list or a specific profile name')
@click.argument('operation', nargs=1)
def main(operation):
    with open(aws / 'profile.json', 'r') as f:
        profiles = json.load(f)

    if operation == 'list':
        list_profiles(profiles)
    else:
        switch_profiles(profiles, operation)


def list_profiles(profiles):
    cp = ConfigParser()
    cp.read(aws / 'credentials')

    print('Available profiles:')
    for k, v in sorted(profiles.items(), key=lambda t: t[0]):
        if v['aws_access_key_id'] == cp.get('default', 'aws_access_key_id', fallback=None):
            print('*', k)
        else:
            print('-', k)


def switch_profiles(profiles, name):
    if name not in profiles:
        raise LookupError(f'Profile "{name}" was not found')

    profile = profiles[name]

    config = ConfigParser()
    config['default'] = {'output': profile['output'], 'region': profile['region']}
    with open(aws / 'config', 'w') as f:
        config.write(f)

    credentials = ConfigParser()
    credentials['default'] = {'aws_access_key_id': profile['aws_access_key_id'], 'aws_secret_access_key': profile['aws_secret_access_key']}
    with open(aws / 'credentials', 'w') as f:
        credentials.write(f)

    print('Switched AWS profile to "%s".' % name)


main()

