#!/usr/bin/env python3

import click
import requests


@click.group()
def cmd():
    pass


@cmd.command(help='List (search) available templates')
@click.argument('query', nargs=1, default=None, required=False)
def list(query):
    res = requests.get('https://www.toptal.com/developers/gitignore/api/list')
    templates = res.text.replace(',', '\n').split('\n')

    if query:
        templates = [t for t in templates if query in t]

    print('\n'.join(templates))


@cmd.command(help='generate gitignore')
@click.argument('templates', nargs=-1)
def generate(templates):
    query = ','.join(templates)
    res = requests.get(f'https://www.toptal.com/developers/gitignore/api/{query}')
    print(res.text)


cmd()

